# Generated by Django 5.2.15 on 2026-06-21 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tour', models.CharField(max_length=255)),
                ('nombre_persona', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('saldo', models.IntegerField()),
                ('cantidad_personas', models.IntegerField()),
                ('adultos', models.IntegerField()),
                ('ninos', models.IntegerField()),
                ('estado', models.CharField(default='pendiente', max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tours.tour')),
            ],
        ),
    ]
