# Generated by Django 5.2.15 on 2026-06-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_es', models.CharField(max_length=255)),
                ('titulo_en', models.CharField(max_length=255)),
                ('descripcion_es', models.TextField()),
                ('descripcion_en', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('imagen_portada', models.ImageField(upload_to='tours/')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
