# Generated by Django 5.2.15 on 2026-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='subcategoria',
            field=models.CharField(default='tierra', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('islas', 'Islas'), ('city', 'City Tours'), ('chivas', 'Chivas'), ('bahia', 'Bahía')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='titulo_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='titulo_es',
            field=models.CharField(max_length=200),
        ),
    ]
