# Generated by Django 5.2.15 on 2026-08-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_subcategoria_alter_tour_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='precio',
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_adulto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_niño',
            field=models.IntegerField(default=0),
        ),
    ]
