# Generated by Django 5.2.15 on 2026-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tour_precio_tour_precio_adulto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='precio_niño',
        ),
        migrations.AddField(
            model_name='tour',
            name='precio_nino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='rango_edad_nino',
            field=models.CharField(blank=True, help_text='Ej: 4 a 10 años', max_length=50, null=True),
        ),
    ]
