# Generated by Django 5.2.15 on 2026-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tour_precio_niño_tour_precio_nino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='subcategoria',
        ),
        migrations.AlterField(
            model_name='tour',
            name='categoria',
            field=models.CharField(choices=[('PASADIAS_MARITIMOS', 'Pasadías Marítimos'), ('CITY_TOURS', 'City Tours'), ('CHIVAS', 'Chivas'), ('TOURS_BAHIA', 'Tours por la Bahía'), ('TERRESTRES_BARU', 'Tours Terrestres Barú'), ('CLASICO_ROSARIO', 'Tour Clásico Isla del Rosario'), ('PUBLICO_ROSARIO', 'Tour Público Isla del Rosario'), ('TIERRA_BOMBA_PUNTA_ARENA', 'Tierra Bomba y Punta Arena')], max_length=100),
        ),
    ]
