# Generated by Django 5.2.15 on 2026-06-21 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='resenas/')),
                ('comentario', models.TextField()),
                ('estrellas', models.IntegerField()),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='tours.tour')),
            ],
        ),
    ]
