# Generated by Django 5.2.15 on 2026-06-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
